{% set name = "grpcio-status" %}
{% set version = "1.75.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grpcio_status-{{ version }}.tar.gz
  sha256: 69d5b91be1b8b926f086c1c483519a968c14640773a0ccdd6c04282515dbedf7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - protobuf >=6.31.1,<7.0.0
    - grpcio >=1.75.0
    - googleapis-common-protos >=1.5.5

test:
  imports:
    - grpc_status
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://grpc.io
  summary: Status proto mapping for gRPC
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Reference package for GRPC Python status proto mapping.

    gRPC Python: https://grpc.io/docs/languages/python/quickstart/
    gRPC Python API: https://grpc.github.io/grpc/python/

    PyPI: [https://pypi.org/project/grpcio-status](https://pypi.org/project/grpcio-status)

  doc_url: https://grpc.io/docs/languages/python/quickstart/
  dev_url: https://github.com/grpc/grpc/tree/master/src/python/grpcio_status

extra:
  recipe-maintainers:
    - sugatoray
    - xylar
