{% set name = "grpcio-status" %}
{% set version = "1.54.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpcio-status-{{ version }}.tar.gz
  sha256: 3255cbec5b7c706caa3d4dd584606c080e6415e15631bb2f6215e2b70055836d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - protobuf >=4.21.6
    - grpcio >={{ version }}
    - googleapis-common-protos >=1.5.5

test:
  imports:
    - grpc_status
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://grpc.io
  summary: Status proto mapping for gRPC
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Reference package for GRPC Python status proto mapping.

    gRPC Python: https://grpc.io/docs/languages/python/quickstart/
    gRPC Python API: https://grpc.github.io/grpc/python/

    PyPI: [https://pypi.org/project/grpcio-status](https://pypi.org/project/grpcio-status)

  doc_url: https://grpc.io/docs/languages/python/quickstart/
  dev_url: https://github.com/grpc/grpc/tree/master/src/python/grpcio_status

extra:
  recipe-maintainers:
    - sugatoray
    - xylar
