{% set name = "grpcio-status" %}
{% set version = "1.51.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpcio-status-{{ version }}.tar.gz
  sha256: 5415b3fa555cd9f0dbfe51bc2b2818cf11c96b5898b103421f6df2fa65108fa2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - googleapis-common-protos >=1.5.5
    - grpcio >={{ version }}
    - protobuf >=4.21.3
    - python >=3.6

test:
  imports:
    - grpc_status
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://grpc.io
  summary: Status proto mapping for gRPC
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Reference package for GRPC Python status proto mapping.

    gRPC Python: https://grpc.io/docs/languages/python/quickstart/
    gRPC Python API: https://grpc.github.io/grpc/python/

    PyPI: [https://pypi.org/project/grpcio-status](https://pypi.org/project/grpcio-status)

  doc_url: https://grpc.io/docs/languages/python/quickstart/
  dev_url: https://github.com/grpc/grpc/tree/master/src/python/grpcio_status

extra:
  recipe-maintainers:
    - hadim
    - sugatoray
    - xylar
