{% set name = "grpcio-status" %}
{% set version = "1.42.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpcio-status-{{ version }}.tar.gz
  sha256: 25533c4d65d7d513a638f0c4b88b2b66700e3bf43e6995a55a3bd15ec0b77902

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - googleapis-common-protos >=1.5.5
    - grpcio >=1.41.1
    - protobuf >=3.6.0
    - python >=3.6

test:
  imports:
    - grpc_status
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://grpc.io
  summary: Status proto mapping for gRPC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
